# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

blocks:
    - type: prompt
      alignment: left
      leading_diamond: 
      trailing_diamond: 
      segments:
        - template: ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'
          foreground: '#ffffff'
          background: '#440044'
          type: os
          style: diamond
        - trailing_diamond: 
          template: ' {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} '
          foreground: '#ffffff'
          background: '#440044'
          type: session
          style: diamond
        - options:
            max_depth: 3
            style: agnoster_short
          trailing_diamond: 
          foreground: '#ffffff'
          background: '#882222'
          type: path
          style: diamond
        - options:
            fetch_stash_count: true
            fetch_status: true
            fetch_upstream_icon: true
          trailing_diamond: 
          template: ' {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
          foreground: '#193549'
          background: '#fffb38'
          type: git
          style: diamond
          background_templates:
            - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}'
            - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}'
            - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
            - '{{ if gt .Behind 0 }}#B388FF{{ end }}'
    - type: prompt
      alignment: left
      leading_diamond: 
      trailing_diamond: 
      segments:
        - trailing_diamond: 
          template: '   {{.Profile}}{{if .Region}}@{{.Region}}{{end}} '
          foreground: '#000000'
          background: '#f5ef42'
          type: aws
          style: diamond
        - trailing_diamond: 
          template: '   {{ .Name }} '
          foreground: '#000000'
          background: '#9ec3f0'
          type: az
          style: diamond
        - options:
            parse_kubeconfig: false
          trailing_diamond: 
          template: " \U000F10FE {{.Context}}{{if .Namespace}} ({{.Namespace}}){{end}} "
          foreground: '#000000'
          background: '#ebcc34'
          type: kubectl
          style: diamond
      newline: true
    - type: prompt
      alignment: left
      segments:
        - options:
            always_enabled: true
          template: ❯
          foreground: '#00ff00'
          type: status
          style: plain
          foreground_templates:
            - '{{ if .Error }}#ff0000{{ end }}'
            - '{{ if gt .Code 0 }}#ff0000{{ end }}'
      newline: true
version: 4
final_space: true
